### ISSUE TITLE
There should be a "balanced" policy!

### ISSUE THREAD

**Issue by KarkanAlzwayed** [Haptein/powerplan#2]
**Is your feature request related to a problem? Please describe.**
There are only these policies ` ['default', 'performance', 'balance_performance', 'balance_power', 'power']`

**Describe the solution you'd like**
A `balance` policy would be great, because `power` makes the laptop too slow and things lag a lot, the `balance_power` is ok, but things still lag a bit, especially Firefox, and `balance_performance` and `performance` consume too much battery. If the `default` one is `balance` one, and the balance_power and balance_performance adjust themselves automatically (in which case I didn't notice that) then you can just disregard this request.

**Describe alternatives you've considered**
`balance_power`

**Additional context**
This gives an error, which indicates that there is no `balance` policy. 
![Screenshot_20211008_222035](https://user-images.githubusercontent.com/49320606/136670767-f53faa5d-42a3-453f-80d8-ff4755fbf3ca.png)

**Comment by Haptein** [comment]
These policies (Energy Performance Preference Policies) are distinct frequency scaling behaviours that come built in the CPU scaling driver (intel_pstate in your and my case). They basically control how aggressively your CPU tries to scale down in frequency , for example in power it tries to go to it's minimum allowed frequency as soon as it has nothing to do, while in the performance biased ones it tries to keep it's frequency higher to be more responsive.

The policies available that powerplan shows are all the EPP policies that your CPU (with intel_pstate) supports. But not that by default powerplan's config set's a computed (60% along the frequency range supported) bat_maxfreq which limits how high your CPU's frequency can go. I'm thinking perhaps that's the reason it feels a bit sluggish. Do you think this freq limit should be higher on battery?

**Comment by KarkanAlzwayed** [comment]
Ok, makes sense. It is something you can't control, however, you can control the percentage of frequency that the CPU can go on battery. The 60% sounds reasonable, but not in my case. I have a 4k screen, and I think 60% isn't enough for it to push all those pixels. I'd say 80% would be ok, or if there is a way to make it dynamic. Meaning, it increases as much as it wants depending on the use case, and which cpu intensive applications are running. Keep in mind, that my device is running on the iGPU (Intel UHD 620), as I don't ever install the Nvidia drivers, even though I have an Nvidia dGPU, because they always cause issues. 
On a side note, I've set it to the `balance_performence` (default) policy and things are much better now. I guess, I'll still with `default`.

**Comment by Haptein** [comment]
> I'd say 80% would be ok, or if there is a way to make it dynamic.
I actually have been designing a system to dynamically change policies and limit frequencies. In my tests it increases my battery life by about 45% when completing the same task (that's the best case scenario in terms of energy savings, but savings are still substantial) compared to standard "just setting powersave/power governor/policy". It sounds nice in principle, but there's still some work left to do since I'd like this to work with the different scaling drivers available. I'll probably document this nicely when finished.

>Meaning, it increases as much as it wants depending on the use case, and which cpu intensive applications are running.
You can already do this tho.

For example if you wanted to increase the frequency limit when running chromium you could add a profile to /etc/powerpla.conf like so:
```
[MyBrowserProfileOrWhatever]
priority = 1
ac_maxfreq = 4000
bat_maxfreq = 4000
triggerapps = chromium, GeckoMain
```
Making a profile overrides the DEFAULT profile values with the ones specified when one of the triggerapps are running. Note that you have to match the process name (which you can find in any system monitor), so the example contains GeckoMain with is the process name of Firefox.

**Comment by KarkanAlzwayed** [comment]
>I actually have been designing a system to dynamically change policies and limit frequencies. In my tests it increases my battery life by about 45% when completing the same task (that's the best case scenario in terms of energy savings, but savings are still substantial) compared to standard "just setting powersave/power governor/policy". It sounds nice in principle, but there's still some work left to do since I'd like this to work with the different scaling drivers available. I'll probably document this nicely when finished.
>
I'd like to test that

>[MyBrowserProfileOrWhatever]
priority = 1
ac_maxfreq = 4000
bat_maxfreq = 4000
triggerapps = chromium, GeckoMain
>
Do I add this under the whole profile like so? 
```
[DEFAULT]
priority = 99
ac_pollingperiod = 4000
bat_pollingperiod = 4000
ac_cores_online = 4
bat_cores_online = 4
ac_templimit = 95
bat_templimit = 95
ac_minfreq = 400
ac_maxfreq = 4000
bat_minfreq = 400
bat_maxfreq = 3000
ac_minperf = 1
ac_maxperf = 100
bat_minperf = 1
bat_maxperf = 96
ac_tdp_sustained = 0
ac_tdp_burst = 0
bat_tdp_sustained = 0
bat_tdp_burst = 0
ac_turbo = True
bat_turbo = False
ac_governor = powersave
bat_governor = powersave
ac_policy = balance_performance
bat_policy = default
triggerapps = 

[MyBrowserProfileOrWhatever]
priority = 1
ac_maxfreq = 4000
bat_maxfreq = 4000
triggerapps = chromium, GeckoMain
```
Or how do I go about adding it?

**Comment by Haptein** [comment]
Yes, just like that 👍. You can add any of the keys in the DEFAULT profile, and you can add any number of profiles.
