### ISSUE TITLE
[Bug] IndexError: tuple index out of range in cpu.py

### ISSUE THREAD

**Issue by monarc99** [Haptein/powerplan#4]
**Description**
if i start powerplan on my Intel(R) Core(TM) i5-3550, i get the error:

Traceback (most recent call last):
  File "/usr/bin/powerplan", line 10, in <module>
    import status
  File "/opt/powerplan/src/status.py", line 8, in <module>
    import cpu
  File "/opt/powerplan/src/cpu.py", line 418, in <module>
    CPU = CPUSpec()
  File "/opt/powerplan/src/cpu.py", line 84, in __init__
    self.sibling_cores_repr = ' '.join([f"{sib[0]}-{sib[1]}" for sib in self.thread_siblings])
  File "/opt/powerplan/src/cpu.py", line 84, in <listcomp>
    self.sibling_cores_repr = ' '.join([f"{sib[0]}-{sib[1]}" for sib in self.thread_siblings])
IndexError: tuple index out of range

my cpu is old, really old. Only 1 thread per core. I think powerplan expects always 2 threads.

**Additional info:**
ouput of lscpu:

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         36 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz
    CPU family:          6
    Model:               58
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            9
    CPU max MHz:         3700,0000
    CPU min MHz:         1600,0000
    BogoMIPS:            6797.62
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good 
                         nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f1
                         6c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    1 MiB (4 instances)
  L3:                    6 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
  Mds:                   Mitigation; Clear CPU buffers; SMT disabled
  Meltdown:              Mitigation; PTI
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
  Srbds:                 Vulnerable: No microcode
  Tsx async abort:       Not affected

**Comment by monarc99** [comment]
it does not stop at the error, but another one :)

i try your tool on a normal desktop without battery. But i have a wireless mouse and keyboard.
i would be interested in switching power configurations on desktop depending on temperature (later), specified running processes and the current workload (later)

i get the error:

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/bin/powerplan", line 10, in <module>
    import status
  File "/opt/powerplan/src/status.py", line 9, in <module>
    import powersupply
  File "/opt/powerplan/src/powersupply.py", line 123, in <module>
    CURRENT_NOW = BAT.with_name('current_now')
AttributeError: 'NoneType' object has no attribute 'with_name'

-----------------------------------------------------------------------------

with your new powersupply branch i get:

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/bin/powerplan", line 10, in <module>
    import status
  File "/opt/powerplan/src/status.py", line 9, in <module>
    import powersupply
  File "/opt/powerplan/src/powersupply.py", line 313, in <module>
    AC, BAT = power_supply_detection()
  File "/opt/powerplan/src/powersupply.py", line 266, in power_supply_detection
    return ACAdapter(ac_path), Battery(bat_path)
  File "/opt/powerplan/src/powersupply.py", line 42, in __init__
    self.name = path.name
AttributeError: 'NoneType' object has no attribute 'name'

-----------------------------------------------------------------------------

in  /sys/class/power_supply/ 
are my wireless mouse/keyboard

-----------------------------------------------------------------------------

hidpp_battery_0  
hidpp_battery_1

-----------------------------------------------------------------------------

content of hidpp_battery_0

-----------------------------------------------------------------------------

==> /sys/class/power_supply/hidpp_battery_0/capacity_level <==
Full
==> /sys/class/power_supply/hidpp_battery_0/manufacturer <==
Logitech
==> /sys/class/power_supply/hidpp_battery_0/model_name <==
MX Keys Wireless Keyboard
==> /sys/class/power_supply/hidpp_battery_0/online <==
1
==> /sys/class/power_supply/hidpp_battery_0/scope <==
Device
==> /sys/class/power_supply/hidpp_battery_0/status <==
Discharging
==> /sys/class/power_supply/hidpp_battery_0/type <==
Battery
==> /sys/class/power_supply/hidpp_battery_0/uevent <==
POWER_SUPPLY_NAME=hidpp_battery_0
POWER_SUPPLY_TYPE=Battery
POWER_SUPPLY_ONLINE=1
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_SCOPE=Device
POWER_SUPPLY_MODEL_NAME=MX Keys Wireless Keyboard
POWER_SUPPLY_MANUFACTURER=Logitech
POWER_SUPPLY_CAPACITY_LEVEL=Full

-----------------------------------------------------------------------------

maybe /sys/class/power_supply/hidpp_battery_0/scope = Device ?

**Comment by Haptein** [comment]
I thought it'd take longer, the powersupply should be ready for merging. I'd be grateful If you could test it 🤖

**Comment by monarc99** [comment]
i get:

-------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/bin/powerplan", line 10, in <module>
    import status
  File "/opt/powerplan/src/status.py", line 24, in <module>
    Policies:\t\t{', '.join(CPU.policies)}
AttributeError: 'CPUSpec' object has no attribute 'policies'

-------------------------------------------------------------------------
