### ISSUE TITLE
Is it possible to integrate powerplan into KDE's panel and settings?

### ISSUE THREAD

**Issue by KarkanAlzwayed** [Haptein/powerplan#9]
I hope I will make sense, but here it is.
On kde, when I install `power-profiles-daemon`, kde would detect it and add a section for it in the panel and the settings, where I can switch profiles directly from the panel, and also set default profiles when power is plugged/unplugged. Could something similar possibly be done with `powerplan` via a package that I can download? A script that I can run? A merge/pull request or something you developers do? 
It is a really nice feature, but I just can't use `power-profiles-daemon`(PFD) over `powerplan`, because PFD makes my laptop's fans go bananas after the power is plugged in. Powerplan doesn't do that.
See screenshots, please

Panel integration
![panel](https://user-images.githubusercontent.com/49320606/141333063-801799fe-d3e2-46c4-928a-1472959b6a76.png)

settings integration
To make changes while on AC or battery power
![when on battery](https://user-images.githubusercontent.com/49320606/141333126-6b72edfd-2722-408e-a711-bc698bfafcbc.png)

To set default profiles when on AC or battery power (power plugged/unplugged)
![switch](https://user-images.githubusercontent.com/49320606/141333149-af8c32e2-295f-4caa-ac73-97148f4c13a4.png)

**Comment by Haptein** [comment]
I've never used KDE before (although it's tempting me 🤤), and I wonder if there's some easy way to customize it, perhaps some widget standard or the like. Is this panel user customizable? On the other hand, adding a tray icon/menu to the GUI (a potential future) is entirely possible also being compatible with other DE's.

**Comment by KarkanAlzwayed** [comment]
You are missing out on the fun if you have never used KDE. To me personally, it is the best DE there is, period. That panel is a dock called "latte-dock" (another fantastic addition to KDE), and it is extremely customizable, just like KDE itself. If I were you, I'd sift through the various parts of KDE code and see if it is something you can do. I'd even get in touch with the devs to see if they can help you make it happen, they are some of the friendliest out there. They have their own chat on element [here](https://webchat.kde.org/#/room/#kde-devel:kde.org) if you want to ask questions.

**Comment by Haptein** [comment]
I'd personally like to keep this repo DE agnostic, so that'd have to be it's own proyect. I honestly don't think I'd have enough time for DE specific interface implementations, but I'd happily help anyone willing to make something like that happen.

> You are missing out on the fun if you have never used KDE. 

I really enjoy customizing my DE so that's nice to hear. Maybe some day I'll make some time to try it.

**Comment by KarkanAlzwayed** [comment]
Maybe a kde applet then? I'd take that, too. Try kde in a vm, I think it is the most customizable DE out there.
